services:
  valheim:
    image: ghcr.io/community-valheim-tools/valheim-server
    cap_drop:
      - ALL
      - SYS_MODULE
    cap_add:
      - sys_nice
      - CHOWN
      - SETUID
      - SETGID
      - KILL
    volumes:
      - $HOME/valheim-server/config:/config
      - $HOME/valheim-server/data:/opt/valheim
    ports:
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
    env_file:
      - $HOME/valheim-server/valheim.env
    restart: always
    stop_grace_period: 2m
