version: "3.9"
services:
  valheim:
    image: lloesche/valheim-server
    volumes:
      - /path/to/valheim/settings:/config
      # The volume mount below is mandatory for V+ so that you can modify the config file for the mod
      - /path/to/valheim/server:/opt/valheim
    ports:
      - "2456-2458:2456-2458/udp"
    environment:
      - SERVER_NAME=Server Name
      - SERVER_PASS=secret
      - SERVER_PUBLIC=1
      - SERVER_PORT=2456
      - WORLD_NAME=Testing
      - VALHEIM_PLUS_ENABLED=false
