#!/bin/bash
# Fix permissions in case they were altered externaly
echo "Running Valheim Server updater as user $USER uid $UID"
CONFIG_DIRECTORY_PERMISSIONS=${CONFIG_DIRECTORY_PERMISSIONS:-755}
WORLDS_DIRECTORY_PERMISSIONS=${WORLDS_DIRECTORY_PERMISSIONS:-755}
WORLDS_FILE_PERMISSIONS=${WORLDS_FILE_PERMISSIONS:-644}
UPDATE_INTERVAL=${UPDATE_INTERVAL:-900}
STEAMCMD_ARGS=${STEAMCMD_ARGS-validate}
just_started=true
next_update=$(date +%s)

cd /opt/steamcmd
main() {
    while :; do
        update_permissions
        update
        next_update=$(($(date +%s)+$UPDATE_INTERVAL))
        while [ $(date +%s) -lt $next_update ]; do
            sleep 5
        done
    done
}

update() {
    local logfile="$(mktemp)"
    echo "Updating/Validating Valheim Server"
    ./steamcmd.sh +login anonymous +force_install_dir /opt/valheim_dl +app_update 896660 $STEAMCMD_ARGS +quit
    rsync -a --itemize-changes --delete --exclude server_exit.drp --exclude steamapps /opt/valheim_dl/ /opt/valheim | tee "$logfile"
    grep '^[*>]' "$logfile" > /dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo "Valheim Server was updated - restarting"
        supervisorctl restart valheim-server
    else
        echo "Valheim Server is already the latest version"
        if [ $just_started = true ]; then
            supervisorctl start valheim-server
        fi
    fi
    just_started=false
    rm -f "$logfile"
}

update_permissions() {
    chmod $CONFIG_DIRECTORY_PERMISSIONS /config
    if [ -d /config/worlds ]; then
        chmod $WORLDS_DIRECTORY_PERMISSIONS /config/worlds
        chmod $WORLDS_FILE_PERMISSIONS /config/worlds/*
    fi
}

update_now() {
    echo "Received signal to check for update"
    next_update=$(date +%s)
}

trap update_now SIGHUP
main
