#!/bin/bash
# Fix permissions in case they were altered externaly
echo "Running Valheim Server updater as user $USER uid $UID"
CONFIG_DIRECTORY_PERMISSIONS=${CONFIG_DIRECTORY_PERMISSIONS:-755}
WORLDS_DIRECTORY_PERMISSIONS=${WORLDS_DIRECTORY_PERMISSIONS:-755}
WORLDS_FILE_PERMISSIONS=${WORLDS_FILE_PERMISSIONS:-644}
UPDATE_INTERVAL=${UPDATE_INTERVAL:-900}
STEAMCMD_ARGS=${STEAMCMD_ARGS}
FORCE_VALIDATE=${FORCE_VALIDATE:-false}
VALHEIM_PLUS_ENABLED=${VALHEIM_PLUS_ENABLED:-true}
just_started=true
next_update=$(date +%s)

cd /opt/steamcmd
main() {
    while :; do
        update_permissions
        update_valheim
        if [ $VALHEIM_PLUS_ENABLED = true ]; then
            update_valheim_plus
        fi
        next_update=$(($(date +%s)+$UPDATE_INTERVAL))
        while [ $(date +%s) -lt $next_update ]; do
            sleep 5
        done
    done
}

install_valheim_plus() {
    echo "Installing/Updating Valheim Plus"
    wget -q -O /opt/valheimplus/UnixServer.zip https://github.com/nxPublic/ValheimPlus/releases/latest/download/UnixServer.zip && \
    unzip -qo /opt/valheimplus/UnixServer.zip -x changelog.txt run_bepinex.sh -d /opt/valheimplus
    if [ -f /opt/valheim/BepInEx/config/valheim_plus.cfg ]; then
        cp -a /opt/valheim/BepInEx/config/valheim_plus.cfg /opt/valheimplus/BepInEx/config/valheim_plus.cfg
    fi
    chmod 666 /opt/valheimplus/BepInEx/config/valheim_plus.cfg
    rsync -a --itemize-changes --exclude UnixServer.zip /opt/valheimplus/ /opt/valheim
}

update_valheim_plus() {
    remote_md5="$(curl -sL https://github.com/nxPublic/ValheimPlus/releases/latest/download/UnixServer.zip | md5sum | cut -d ' ' -f 1)"
    local_md5="$(md5sum /opt/valheimplus/UnixServer.zip | cut -d ' ' -f 1)"
    if [ "$remote_md5" != "$local_md5" ]; then
        install_valheim_plus
    else
        echo "Valheim Plus is already the latest version"
    fi
}

install_valheim() {
    ./steamcmd.sh +login anonymous +force_install_dir /opt/valheim +app_update 896660 $1 $STEAMCMD_ARGS +quit
    if [ $VALHEIM_PLUS_ENABLED = true ]; then
        install_valheim_plus
    fi
    echo "Valheim Server was updated - restarting"
    supervisorctl restart valheim-server
}

update_valheim() {
    if [ ! -d /opt/valheim/valheim_server_Data ] || [ $FORCE_VALIDATE = true ]; then
        echo "Installing Valheim Server"
        args=""
        if [ $FORCE_VALIDATE = true ]; then
            args=-validate
            FORCE_VALIDATE=false
        fi
        install_valheim $args
    else
        local_version=$(awk '/"896661"/,/"manifest"/{if($1=="\"manifest\"")print $2;}' /opt/valheim/steamapps/appmanifest_896660.acf | xargs)
        ./steamcmd.sh +login anonymous +force_install_dir /opt/valheim +app_update 896660 $STEAMCMD_ARGS +quit
        remote_version=$(./steamcmd.sh +login anonymous +app_info_update 1 +app_info_print 896660 +quit | awk '/"896661"/,/"public"/{if($1=="\"manifest\"")print $2;}' | xargs)
        if [ "$local_version" != "$remote_version" ]; then
            echo "Updating/Validating Valheim Server"
            install_valheim -validate
        else
            echo "Valheim Server is already the latest version"
            if [ $just_started = true ]; then
                supervisorctl start valheim-server
            fi
        fi
    fi
    just_started=false
}

update_permissions() {
    chmod $CONFIG_DIRECTORY_PERMISSIONS /config
    if [ -d /config/worlds ]; then
        chmod $WORLDS_DIRECTORY_PERMISSIONS /config/worlds
        chmod $WORLDS_FILE_PERMISSIONS /config/worlds/*
    fi
}

update_now() {
    echo "Received signal to check for update"
    next_update=$(date +%s)
}

trap update_now SIGHUP
main
