#!/bin/bash
. /usr/local/etc/valheim/defaults
. /usr/local/etc/valheim/common

main() {
    timeout=900
    echo "Running tests..."
    echo "Waiting up to $timeout seconds for server to start..."
    start_time=$(date +%s)
    while :; do
        if server_is_listening; then
            echo "Server is now listening on UDP port $SERVER_QUERY_PORT"
            break
        fi
        sleep 1
        current_time=$(date +%s)
        if [ $((current_time - start_time)) -ge $timeout ]; then
            echo "Server did not start listening on UDP port $SERVER_QUERY_PORT within $timeout seconds"
            exit 1
        fi
    done
    echo "Tests passed!"
    exit 0
}

main
